ShowReadingTime: true
ShowBreadCrumbs: true
ShowCodeCopyButtons: true
ShowPostNavLinks: false

assets:
  favicon: ./favicon/favicon.ico?
  favicon16x16: ./favicon/favicon-16x16.png?
  favicon32x32: ./favicon/favicon-32x32.png?
  apple_touch_icon: ./favicon/apple-touch-icon.png?
  safari_pinned_tab: ./favicon/safari-pinned-tab.svg? 

# label:
#   text: aa # replace header
#   icon: favicon-32x32.png