baseURL = 'http://krb3d.dev/'
languageCode = 'en-us'
title = 'krb3d.dev'
theme = "PaperMod"

[params]
defaultTheme = 'light'

[[socialIcons]]
name = "kofi"
url = "https://kofi.com"

[[socialIcons]]
name = "twitter"
url = "https://twitter.com"


[[socialIcons.linkedin]]
url = "https://linkedin.com/in/krb3d"
